Lab Session 3

1) Navie Bayes

In this example, we will use the Naive Bayes algorithm to predict whether a person will play or not based on the weather conditions. The dataset contains the following attributes:

In [1]:
import pandas as pd

#Creat dataset
Weather_dataset = {
    'weather': ['sunny', 'sunny', 'overcast', 'rainy', 'rainy', 'rainy', 'overcast', 'sunny', 'sunny', 'rainy', 'sunny',
                'overcast', 'overcast', 'rainy'],
    'temperature': ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot',
                    'Mild'],
    'play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']
}
Weather_dataset = pd.DataFrame(Weather_dataset)

display(Weather_dataset)

weather temperature play
0      sunny         Hot   No
1      sunny         Hot   No
2   overcast         Hot  Yes
3      rainy        Mild  Yes
4      rainy        Cool  Yes
5      rainy        Cool   No
6   overcast        Cool  Yes
7      sunny        Mild  Yes
8      sunny        Cool  Yes
9      rainy        Mild  Yes
10     sunny        Mild  Yes
11  overcast        Mild  Yes
12  overcast         Hot  Yes
13     rainy        Mild   No

We need to encode the features [Weather, Temperature], and target by converting string labels into numbers.

In [2]:
#Import LabelEncoder
from sklearn import preprocessing

#creating labelEncoder
labelEncoder = preprocessing.LabelEncoder()

# Converting string labels into numbers.
encoded_weather = labelEncoder.fit_transform(Weather_dataset['weather'])
encoded_temperature = labelEncoder.fit_transform(Weather_dataset['temperature'])
encoded_play = labelEncoder.fit_transform(Weather_dataset['play'])

#print data
encoded_weather, encoded_temperature, encoded_play

(array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1]),
 array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2]),
 array([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0]))

In [3]:
#encoded features are the combined
features = [list(i) for i in zip(encoded_weather, encoded_temperature)]

Next we generate a model using navie bayes classifier

In [4]:
#Import Categorical Navie Bays model
from sklearn.naive_bayes import CategoricalNB

#Creat the model
model = CategoricalNB()

#Train the model
model.fit(features, encoded_play)

CategoricalNB()

Our model is ready to be tested

In [7]:
#Predict Output (sunny and hot)
predicted = model.predict([[0, 1]])  # 0:Overcast, 2:Mild
print("Can I play?", labelEncoder.inverse_transform(predicted))

predicted = model.predict([[1, 0]])  # 0:rain, 2:cold
print("Can I play?", labelEncoder.inverse_transform(predicted))

Can I play? ['Yes']
Can I play? ['Yes']


Exercise 1

In this exercise you will train a Navie Bayes model using the blood_tranfusion dataset https://github.com/INRIA/scikit-learn-mooc/blob/main/datasets/blood_transfusion.csv

1) Import the blood_transfusion dataset, and display the donated and not donated samples
2) Train your Naive Bayes model
3) Predict the class for this following vectors (0, 500, 1000, 28) and (4,10, 4000, 64)

In [8]:
#Import the blood_transfusion dataset, and display the donated and not donated samples

blood_transfusion = pd.read_csv("./datasets/blood_transfusion.csv")

blood_transfusion.sample(10)

Recency  Frequency  Monetary  Time        Class
747       72          1       250    72  not donated
219        4          1       250     4  not donated
229        4          1       250     4  not donated
452       23          2       500    28  not donated
175       11         10      2500    35  not donated
477       23          1       250    23  not donated
623       11          6      1500    28  not donated
516        3          5      1250    12      donated
489       21          3       750    64  not donated
536        2          7      1750    32      donated

In [9]:
#Train your Naive Bayes model

#creating labelEncoder
labelEncoderBlood = preprocessing.LabelEncoder()

# Converting string labels into numbers.
encoded_recency = labelEncoderBlood.fit_transform(blood_transfusion['Recency'])
encoded_frequency = labelEncoderBlood.fit_transform(blood_transfusion['Frequency'])
encoded_monetary = labelEncoderBlood.fit_transform(blood_transfusion['Monetary'])
encoded_time = labelEncoderBlood.fit_transform(blood_transfusion['Time'])
encoded_class = labelEncoderBlood.fit_transform(blood_transfusion['Class'])

#encoded features are the combined
features_blood = [list(i) for i in zip(encoded_recency, encoded_frequency, encoded_monetary, encoded_time)]

#Creat the model
modelBlood = CategoricalNB()

#Train the model
modelBlood.fit(features_blood, encoded_class)

CategoricalNB()

In [10]:
#Predict the class for this following vectors (0, 500, 1000, 28) and (4,10, 4000, 64)

#Predict Output (0, 500, 1000, 28)
predicted = modelBlood.predict([[0, 500, 1000, 28]])
print("Can I donate?", labelEncoderBlood.inverse_transform(predicted))

#Predict Output (4,10, 4000, 64)
predicted = modelBlood.predict([[4, 10, 4000, 64]])
print("Can I donate?", labelEncoderBlood.inverse_transform(predicted))

IndexError: index 500 is out of bounds for axis 1 with size 33

Exercise 2

Marks secured by students in highschool are classified according to different caracteristics (gender, race, etc), take a look at the dataset : https://raw.githubusercontent.com/rashida048/Datasets/master/StudentsPerformance.csv

1) Does parental level of education affect the reading score ?
2) Does test preparation course help to score better ?
3) What is the ethnicity of students ?
4) Using th Navie Bayes method, train your model to predict the different scores (math, reading, writing) of the following students caracteristics :
- [female, group A, some college, free/reduced, completed]
- [male, group D, high school, standard, none]
- [female, group B, associate's degree, standard, none]
- [male, group C, master's degree, free/reduced, none]

In [18]:
##Unique value of each column
studentsPerformance = pd.read_csv("./datasets/StudentsPerformance.csv")

uniqueValeur = []

for col in studentsPerformance.columns:
    uniqueValeur.append([col, studentsPerformance[col].unique()])

print(uniqueValeur)

[['gender', array(['female', 'male'], dtype=object)], ['race/ethnicity', array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)], ['parental level of education', array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)], ['lunch', array(['standard', 'free/reduced'], dtype=object)], ['test preparation course', array(['none', 'completed'], dtype=object)], ['math score', array([ 72,  69,  90,  47,  76,  71,  88,  40,  64,  38,  58,  65,  78,
        50,  18,  46,  54,  66,  44,  74,  73,  67,  70,  62,  63,  56,
        97,  81,  75,  57,  55,  53,  59,  82,  77,  33,  52,   0,  79,
        39,  45,  60,  61,  41,  49,  30,  80,  42,  27,  43,  68,  85,
        98,  87,  51,  99,  84,  91,  83,  89,  22, 100,  96,  94,  48,
        35,  34,  86,  92,  37,  28,  24,  26,  95,  36,  29,  32,  93,
        19,  23,   8])], ['reading score', array([ 72,  90,  95,  57,  78,  83

In [25]:
#Does parental level of education affect the reading score ?

##Lire colonne Parental level of education : "bachelor's degree", 'some college', "master's degree", "associate's degree", 'high school', 'some high school'

resScoreReading = []

for element in uniqueValeur[2][1]:
    resScoreReading.append([element, []])
    for row in studentsPerformance.values:
        if element == row[2]:
            resScoreReading[-1][1].append(row[5])

for element in resScoreReading:
    print(element[0], " : ", sum(element[1]) / len(element[1]))

bachelor's degree  :  69.38983050847457
some college  :  67.1283185840708
master's degree  :  69.7457627118644
associate's degree  :  67.88288288288288
high school  :  62.13775510204081
some high school  :  63.497206703910614


In [26]:
#Does test preparation course help to score better ?

resPrepa = [[], []]  #0 = none, 1 = completed

for row in studentsPerformance.values:
    if row[4] == "none":
        resPrepa[0].append(row[5])
    else:
        resPrepa[1].append(row[5])

print("none : ", sum(resPrepa[0]) / len(resPrepa[0]))
print("completed : ", sum(resPrepa[1]) / len(resPrepa[1]))

none :  64.0778816199377
completed :  69.69553072625699


In [ ]:
#What is the ethnicity of students ?


In [55]:
#Entraine model

#creating labelEncoder
labelEncoderScore = preprocessing.LabelEncoder()

# Converting string labels into numbers.
encoded_gender = labelEncoderScore.fit_transform(studentsPerformance['gender'])
encoded_race = labelEncoderScore.fit_transform(studentsPerformance['race/ethnicity'])
encoded_parental = labelEncoderScore.fit_transform(studentsPerformance['parental level of education'])
encoded_lunch = labelEncoderScore.fit_transform(studentsPerformance['lunch'])
encoded_prep = labelEncoderScore.fit_transform(studentsPerformance['test preparation course'])

encoded_math = labelEncoderScore.fit_transform(studentsPerformance['math score'])
encoded_reading = labelEncoderScore.fit_transform(studentsPerformance['reading score'])
encoded_writing = labelEncoderScore.fit_transform(studentsPerformance['writing score'])

#encoded_gender : female = 0, male = 1
#encoded_race : A = 0, B = 1, C = 2, D = 3
#encoded_parental : some college = 0, some high school = 1, high school = 2, associate's degree = 3, bachelor's degree = 4, master's degree = 5
#encoded_lunch : standard = 0, free/reduced = 1
#encoded_prep : none = 0, completed = 1

#encoded features are the combined
featuresStudent = [list(i) for i in zip(encoded_gender, encoded_race, encoded_parental, encoded_lunch, encoded_prep)]


groupe = [encoded_math, encoded_reading, encoded_writing]
matiere = ["Maths", "Reading", "Writing"]

def note(groupe, param, matiere):
    k = 0
    for element in groupe:
        #Creat the model
        modelStudent = CategoricalNB()
        #Train the model
        modelStudent.fit(featuresStudent, element)
        #Predict Output (sunny and hot)
        predicted1 = modelStudent.predict(param)
        print("Note ?", matiere[k], labelEncoderScore.inverse_transform(predicted1))
        k += 1


In [58]:
#Using th Navie Bayes method, train your model to predict the different scores (math, reading, writing) of the following students caracteristics :

print('[female, group A, some college, free/reduced, completed]')
note(groupe, [[0, 0, 0, 1, 1]], matiere)

#[male, group D, high school, standard, none]
note(groupe, [[1, 3, 2, 0, 0]], matiere)

print('female, group B, associate\'s degree, standard, none')
note(groupe, [[0, 1, 3, 0, 0]], matiere)

print('[male, group C, master\'s degree, free/reduced, none]')

note(groupe, [[1, 2, 5, 1, 0]], matiere)

[female, group A, some college, free/reduced, completed]
Note ? Maths [69]
Note ? Reading [69]
Note ? Writing [73]
Note ? Maths [78]
Note ? Reading [62]
Note ? Writing [60]
female, group B, associate's degree, standard, none
Note ? Maths [56]
Note ? Reading [81]
Note ? Writing [87]
[male, group C, master's degree, free/reduced, none]
Note ? Maths [71]
Note ? Reading [80]
Note ? Writing [77]


2) LDA

in this example we use the iris dataset to train an LDA model

In [62]:
#Import Library
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

#load iris dataset
iris = load_iris()

#convert dataset to pandas dataframe
df = pd.DataFrame(data = np.c_[iris['data'], iris['target']],
                  columns = iris['feature_names'] + ['target'])
df['species']= pd.Categorical.from_codes(iris.target, iris.target_names)
df.columns = ['s_length', 's_width', 'p_length', 'p_width', 'target', 'species']

x = df[['s_length', 's_width', 'p_length', 'p_width']]
y = df['target']

#difine data to plot
X = iris.data
Y = iris.target

model = LinearDiscriminantAnalysis()
data_plot = model.fit(X, y).transform(X)
target_names = iris.target_names

After LDA transformation, we can plot our new dataset